# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "Pro Checkout Countdown"
handle = "checkout-timer"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.js"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
    [[extensions.settings.fields]]
    key = "timer_title"
    type = "single_line_text_field"
    name = "Timer Text"
    description = "use {{timer}} to display current running timer"
    default = "Your cart will expire in {{timer}}"
    [[extensions.settings.fields]]
    key = "timer_expire"
    type = "number_integer"
    name = "Timer Expire in"
    default = 20
    description = "In Minutes"
    [[extensions.settings.fields]]
    key = "timer_type"
    type = "single_line_text_field"
    name = "Timer Type"
    description = "Please select only 'info' | 'success' | 'warning' | 'critical'"
    default = "warning"
        [[extensions.settings.fields.validations]]
        name = "choices"
        value = "[\"info\", \"success\", \"warning\", \"critical\"]"
